# Generated by Django 6.1 on 2026-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
